In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
warnings.filterwarnings("ignore")

In [139]:
filter_path =("hotel_revenue.xlsx")
dataframes = pd.read_excel(filter_path,sheet_name=None)
print(dataframes)

{'2018':               hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            1         85               2018
1      Resort Hotel            1         75               2018
2      Resort Hotel            1         23               2018
3      Resort Hotel            1         60               2018
4      Resort Hotel            1         96               2018
...             ...          ...        ...                ...
21991    City Hotel            1         24               2018
21992    City Hotel            1          1               2018
21993    City Hotel            1         66               2018
21994    City Hotel            1         54               2018
21995    City Hotel            1         54               2018

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                   July                        27                          1
1                   July                        27                          1
2                   July                        27                          1
3                   July                        27                          1
4                   July                        27                          1
...                  ...                       ...                        ...
21991           December                        53                         27
21992           December                        53                         27
21993           December                        53                         28
21994           December                        53                         30
21995           December                        53                         30

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     3       2  ...
1                            0                     3       2  ...
2                            0                     4       2  ...
3                            2                     5       2  ...
4                            2                     8       2  ...
...                        ...                   ...     ...  ...
21991                        2                     1       2  ...
21992                        2                     4       2  ...
21993                        0                     5       2  ...
21994                        1                     4       2  ...
21995                        1                     4       2  ...

       deposit_type  agent company days_in_waiting_list customer_type     adr  \
0        No Deposit  240.0     NaN                    0     Transient   82.00
1        No Deposit   15.0     NaN                    0     Transient  105.50
2        No Deposit  240.0     NaN                    0     Transient  123.00
3        No Deposit  240.0     NaN                    0     Transient  107.00
4        No Deposit    NaN     NaN                    0     Transient  108.30
...             ...    ...     ...                  ...           ...     ...
21991    No Deposit   28.0     NaN                    0     Transient   58.00
21992    No Deposit    NaN     NaN                    0     Transient  147.67
21993    No Deposit    9.0     NaN                    0     Transient  170.90
21994    No Deposit    9.0     NaN                    0      Contract  118.20
21995    No Deposit    9.0     NaN                    0      Contract  118.20

       required_car_parking_spaces  total_of_special_requests  \
0                                0                          1
1                                0                          0
2                                0                          0
3                                0                          2
4                                0                          2
...                            ...                        ...
21991                            0                          0
21992                            0                          0
21993                            0                          1
21994                            0                          1
21995                            0                          1

       reservation_status reservation_status_date
0                Canceled              2018-05-06
1                Canceled              2018-04-22
2                Canceled              2018-06-23
3                Canceled              2018-05-11
4                Canceled              2018-05-29
...                   ...                     ...
21991             No-Show              2018-12-27
21992             No-Show              2018-12-27
21993             No-Show              2018-12-29
21994             No-Show              2018-12-30
21995             No-Show              2018-12-30

[21996 rows x 32 columns], '2019':               hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            1         20               2019
1      Resort Hotel            1         76               2019
2      Resort Hotel            1        113               2019
3      Resort Hotel            1        113               2019
4      Resort Hotel            1        113               2019
...             ...          ...        ...                ...
79259  Resort Hotel            1         61               2019
79260  Resort Hotel            1        219               2019
79261  Resort Hotel            1        219               2019
79262  Resort Hotel            1        219               2019
79263  Resort Hotel            1        118               2019

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                January                         1                          1
1                January                         1                          1
2                January                         1                          2
3                January                         1                          2
4                January                         1                          2
...                  ...                       ...                        ...
79259              March                        10                          1
79260              March                        10                          2
79261              March                        10                          2
79262              March                        10                          2
79263              March                        10                          2

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            0                     2       2  ...
1                            1                     2       2  ...
2                            0                     1       2  ...
3                            0                     1       2  ...
4                            0                     1       2  ...
...                        ...                   ...     ...  ...
79259                        4                    10       2  ...
79260                        2                     5       2  ...
79261                        2                     5       2  ...
79262                        2                     5       2  ...
79263                        2                     5       2  ...

       deposit_type  agent company days_in_waiting_list customer_type     adr  \
0        No Deposit  240.0     NaN                    0     Transient  119.00
1        No Deposit  240.0     NaN                    0     Transient   57.90
2        Non Refund  305.0     NaN                    0     Transient   72.00
3        Non Refund  305.0     NaN                    0     Transient   72.00
4        Non Refund  305.0     NaN                    0     Transient   72.00
...             ...    ...     ...                  ...           ...     ...
79259    No Deposit  171.0     NaN                    0     Transient   29.00
79260    Non Refund  310.0     NaN                    0     Transient   52.00
79261    Non Refund  310.0     NaN                    0     Transient   52.00
79262    Non Refund  310.0     NaN                    0     Transient   52.00
79263    No Deposit  241.0     NaN                    0     Transient   33.26

       required_car_parking_spaces  total_of_special_requests  \
0                                0                          0
1                                0                          1
2                                0                          0
3                                0                          0
4                                0                          0
...                            ...                        ...
79259                            0                          0
79260                            0                          0
79261                            0                          0
79262                            0                          0
79263                            0                          0

       reservation_status reservation_status_date
0                Canceled              2018-12-22
1                Canceled              2018-12-20
2                Canceled              2018-11-16
3                Canceled              2018-11-16
4                Canceled              2018-11-16
...                   ...                     ...
79259           Check-Out              2019-01-06
79260           Check-Out              2018-11-20
79261           Check-Out              2018-11-20
79262           Check-Out              2018-11-20
79263           Check-Out              2019-01-27

[79264 rows x 32 columns], '2020':               hotel  is_canceled  lead_time  arrival_date_year  \
0      Resort Hotel            1         74               2020
1      Resort Hotel            1         62               2020
2      Resort Hotel            1         62               2020
3      Resort Hotel            1         62               2020
4      Resort Hotel            1         71               2020
...             ...          ...        ...                ...
40682    City Hotel            1          1               2020
40683    City Hotel            1         31               2020
40684    City Hotel            1         25               2020
40685    City Hotel            1          6               2020
40686    City Hotel            1          0               2020

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                January                         1                          1
1                January                         1                          1
2                January                         1                          1
3                January                         1                          1
4                January                         1                          1
...                  ...                       ...                        ...
40682           February                         5                          1
40683               July                        29                         16
40684                May                        18                          6
40685               July                        29                         17
40686             August                        31                          2

       stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                            1                     0       2  ...
1                            2                     2       2  ...
2                            2                     2       2  ...
3                            2                     2       2  ...
4                            2                     2       1  ...
...                        ...                   ...     ...  ...
40682                        0                     0       1  ...
40683                        2                     0       1  ...
40684                        2                     1       1  ...
40685                        1                     0       1  ...
40686                        0                     2       1  ...

       deposit_type  agent company days_in_waiting_list customer_type     adr  \
0        No Deposit    5.0     NaN                    0     Transient   57.60
1        No Deposit  240.0     NaN                    0     Transient   51.50
2        No Deposit  240.0     NaN                    0     Transient   51.50
3        No Deposit  240.0     NaN                    0     Transient   51.50
4        No Deposit  241.0     NaN                    0     Transient   32.22
...             ...    ...     ...                  ...           ...     ...
40682    No Deposit    NaN   153.0                    0     Transient    0.00
40683    No Deposit    NaN     NaN                    0     Transient  135.00
40684    No Deposit    NaN   450.0                    0     Transient  125.00
40685    No Deposit    NaN   238.0                    0     Transient   65.00
40686    No Deposit    NaN    40.0                    0     Transient   65.00

       required_car_parking_spaces  total_of_special_requests  \
0                                0                          0
1                                0                          1
2                                0                          1
3                                0                          1
4                                0                          1
...                            ...                        ...
40682                            0                          1
40683                            0                          2
40684                            0                          0
40685                            0                          0
40686                            0                          1

       reservation_status reservation_status_date
0                Canceled              2019-10-20
1                Canceled              2019-12-04
2                Canceled              2019-11-11
3                Canceled              2019-12-04
4                Canceled              2019-10-29
...                   ...                     ...
40682             No-Show              2020-02-01
40683             No-Show              2020-07-16
40684             No-Show              2020-05-06
40685             No-Show              2020-07-17
40686             No-Show              2020-08-02

[40687 rows x 32 columns], 'meal_cost':     Cost       meal
0   0.00  Undefined
1  12.99         BB
2  17.99         HB
3  21.99         FB
4  35.00         SC, 'market_segment':    Discount market_segment
0      0.00      Undefined
1      0.10         Direct
2      0.10         Groups
3      0.15      Corporate
4      0.20       Aviation
5      0.30  Offline TA/TO
6      0.30      Online TA
7      1.00  Complementary}

In [140]:
df=dataframes["2020"]

In [141]:
for i in df.describe(include="object").columns:
    print(i)
    print(df[i].unique())

hotel
['Resort Hotel' 'City Hotel']
arrival_date_month
['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August']
meal
['BB' 'HB' 'Undefined' 'FB' 'SC']
country
['PRT' 'AUT' 'ITA' 'BEL' 'GBR' 'DEU' 'BRA' 'IRL' 'ESP' 'FRA' 'AUS' 'LUX'
 'CHE' 'ARG' 'EST' 'CN' 'NLD' 'POL' 'TUR' 'DZA' 'MOZ' 'KOR' 'ROU' 'USA'
 'SWE' 'CHL' 'DNK' 'RUS' 'FIN' 'HUN' 'HRV' 'MDV' 'ZAF' 'CHN' 'NOR' 'VEN'
 'ISR' nan 'SVK' 'ARE' 'MAR' 'AGO' 'COL' 'FJI' 'KAZ' 'LVA' 'PAK' 'URY'
 'NGA' 'IDN' 'SVN' 'LBN' 'PHL' 'LTU' 'HKG' 'SEN' 'SYC' 'CYP' 'GIB' 'AND'
 'GEO' 'AZE' 'BHR' 'SGP' 'IRN' 'DOM' 'UZB' 'GRC' 'UKR' 'BLR' 'MAC' 'TWN'
 'CPV' 'JPN' 'ISL' 'CZE' 'TZA' 'LIE' 'GNB' 'SAU' 'PER' 'EGY' 'ETH' 'KEN'
 'MYS' 'THA' 'MLT' 'IND' 'ECU' 'IMN' 'TUN' 'NZL' 'SRB' 'BGR' 'MNE' 'MEX'
 'KWT' 'BEN' 'UMI' 'JEY' 'OMN' 'BGD' 'MYT' 'JOR' 'QAT' 'GHA' 'FRO' 'GAB'
 'CIV' 'ZWE' 'MDG' 'CAF' 'JAM' 'NPL' 'BHS' 'SUR' 'CUB' 'TGO' 'DJI' 'VNM'
 'GTM' 'ALB' 'ATA' 'ASM' 'PAN' 'CRI' 'MCO' 'MUS' 'SYR' 'IRQ' 'LKA' 'BIH'
 'PRY' 'MRT' 'CMR' 'ABW' 'NCL' 'STP' 'KIR' 'SDN' 'PRI' 'ATF' 'KNA' 'ARM'
 'TJK' 'LBY' 'SLE' 'SLV' 'LAO' 'COM']
market_segment
['Online TA' 'Offline TA/TO' 'Direct' 'Corporate' 'Complementary' 'Groups'
 'Aviation']
distribution_channel
['TA/TO' 'Direct' 'Corporate' 'GDS']
reserved_room_type
['A' 'E' 'G' 'D' 'H' 'F' 'C' 'B' 'P']
assigned_room_type
['A' 'E' 'G' 'D' 'H' 'C' 'F' 'B' 'I' 'K' 'P']
deposit_type
['No Deposit' 'Non Refund' 'Refundable']
customer_type
['Transient' 'Transient-Party' 'Contract' 'Group']
reservation_status
['Canceled' 'Check-Out' 'No-Show']

In [142]:
cancelation_count = df["is_canceled"].value_counts()

not_canceled = cancelation_count[0]
canceled = cancelation_count[1]
print(not_canceled-canceled)

9197

In [143]:
cancelation_by_deposit = df.groupby("deposit_type")["is_canceled"].mean().sort_values(ascending = False)
cancelation_by_deposit

deposit_type
Non Refund    0.998061
Refundable    0.962963
No Deposit    0.317540
Name: is_canceled, dtype: float64

In [144]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [145]:
df["total_stays"] = df["stays_in_weekend_nights"] + df["stays_in_week_nights"]
stay_cancellation_rate = df.groupby("total_stays")["is_canceled"].mean().sort_values(ascending=False)
stay_cancellation_rate

total_stays
26    1.000000
24    1.000000
20    1.000000
18    0.913043
19    0.857143
30    0.857143
29    0.750000
27    0.666667
25    0.611111
28    0.500000
56    0.500000
12    0.487805
3     0.447061
8     0.442105
13    0.432432
2     0.414757
6     0.413077
16    0.411765
9     0.410714
11    0.400000
5     0.389588
10    0.389549
4     0.387771
7     0.383383
15    0.375000
14    0.337580
21    0.312500
1     0.261532
17    0.200000
22    0.200000
0     0.076389
23    0.000000
35    0.000000
38    0.000000
42    0.000000
43    0.000000
45    0.000000
Name: is_canceled, dtype: float64

In [146]:
df["arrival_date"] = pd.to_datetime(
    df["arrival_date_month"].astype(str) + "-" +
    df["arrival_date_day_of_month"].astype(str) + "-" +
    df["arrival_date_year"].astype(str)).dt.day_name()

In [147]:
df.head(2)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_stays,arrival_date
0,Resort Hotel,1,74,2020,January,1,1,1,0,2,...,NaN,0,Transient,57.6,0,0,Canceled,2019-10-20,1,Wednesday
1,Resort Hotel,1,62,2020,January,1,1,2,2,2,...,NaN,0,Transient,51.5,0,1,Canceled,2019-12-04,4,Wednesday

In [148]:
cancellation_counts = df['is_canceled'].value_counts()
canceled = cancellation_counts[1]
not_canceled = cancellation_counts[0]
difference = not_canceled - canceled
print(f"Total Canceled Bookings: {canceled}")
print(f"Total Non-Canceled Bookings: {not_canceled}")
print(f"Difference between Non-Canceled and Canceled: {difference}")

Total Canceled Bookings: 15745
Total Non-Canceled Bookings: 24942
Difference between Non-Canceled and Canceled: 9197

In [149]:
cancellation_rate = df.groupby('previous_cancellations')['is_canceled'].mean()

print("Cancellation Rate based on Previous Cancellations:")
print(cancellation_rate)

Cancellation Rate based on Previous Cancellations:
previous_cancellations
0    0.388453
1    0.174359
2    0.162162
3    0.333333
4    0.315789
5    0.000000
6    0.000000
Name: is_canceled, dtype: float64

In [150]:
market_segment_cancellation_rate = df.groupby('market_segment')['is_canceled'].mean().sort_values(ascending=False).tail(6)

print("Cancellation Rate by Market Segment:")
print(market_segment_cancellation_rate)

Cancellation Rate by Market Segment:
market_segment
Online TA        0.408680
Offline TA/TO    0.337745
Corporate        0.254802
Aviation         0.209091
Complementary    0.163551
Direct           0.154677
Name: is_canceled, dtype: float64

In [151]:
deposit_type_cancellation_rate = df.groupby('deposit_type')['is_canceled'].mean()

print("Cancellation Rate by Deposit Type:")
print(deposit_type_cancellation_rate)

Cancellation Rate by Deposit Type:
deposit_type
No Deposit    0.317540
Non Refund    0.998061
Refundable    0.962963
Name: is_canceled, dtype: float64

In [152]:
special_requests_cancellation_rate = df.groupby('total_of_special_requests')['is_canceled'].mean()

print("Cancellation Rate based on Total of Special Requests:")
print(special_requests_cancellation_rate)

Cancellation Rate based on Total of Special Requests:
total_of_special_requests
0    0.497661
1    0.279648
2    0.256202
3    0.168908
4    0.096939
5    0.045455
Name: is_canceled, dtype: float64

In [153]:
df['room_type_mismatch'] = df['reserved_room_type'] != df['assigned_room_type']
room_type_mismatch_cancellation_rate = df.groupby('room_type_mismatch')['is_canceled'].mean()

print("Cancellation Rate based on Room Type Mismatch:")
print(room_type_mismatch_cancellation_rate)

Cancellation Rate based on Room Type Mismatch:
room_type_mismatch
False    0.41578
True     0.07621
Name: is_canceled, dtype: float64

In [154]:
customer_type_cancellation_rate = df.groupby('customer_type')['is_canceled'].mean()

print("Cancellation Rate by Customer Type:")
print(customer_type_cancellation_rate)

Cancellation Rate by Customer Type:
customer_type
Contract           0.116314
Group              0.064220
Transient          0.432719
Transient-Party    0.171543
Name: is_canceled, dtype: float64

In [155]:
adults_cancellation_rate = df.groupby('adults')['is_canceled'].mean()

print("Cancellation Rate based on Number of Adults:")
print(adults_cancellation_rate)

children_cancellation_rate = df.groupby('children')['is_canceled'].mean()

print("Cancellation Rate based on Number of Children:")
print(children_cancellation_rate)

babies_cancellation_rate = df.groupby('babies')['is_canceled'].mean()

print("Cancellation Rate based on Number of Babies:")
print(babies_cancellation_rate)

Cancellation Rate based on Number of Adults:
adults
0    0.323077
1    0.288985
2    0.408866
3    0.410938
4    0.409091
Name: is_canceled, dtype: float64
Cancellation Rate based on Number of Children:
children
0    0.384441
1    0.368184
2    0.478203
3    0.216216
Name: is_canceled, dtype: float64
Cancellation Rate based on Number of Babies:
babies
0    0.388681
1    0.122530
2    0.000000
Name: is_canceled, dtype: float64

In [156]:
monthly_cancellation_rate = df.groupby('arrival_date_month')['is_canceled'].mean()

print("Cancellation Rate by Arrival Month:")
print(monthly_cancellation_rate)

Cancellation Rate by Arrival Month:
arrival_date_month
April       0.435082
August      0.368731
February    0.325353
January     0.339582
July        0.373424
June        0.431911
March       0.336419
May         0.437510
Name: is_canceled, dtype: float64

In [157]:
year_cancellation_rate = df.groupby(df['reservation_status_date'].dt.year)['is_canceled'].mean()

print("Cancellation Rate by Reservation Year:")
print(year_cancellation_rate)

Cancellation Rate by Reservation Year:
reservation_status_date
2018    1.000000
2019    1.000000
2020    0.308894
Name: is_canceled, dtype: float64

In [158]:
df['total_stays'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
stay_length_cancellation_rate = df.groupby('total_stays')['is_canceled'].mean()

print("Cancellation Rate based on Length of Stay:")
print(stay_length_cancellation_rate)

Cancellation Rate based on Length of Stay:
total_stays
0     0.076389
1     0.261532
2     0.414757
3     0.447061
4     0.387771
5     0.389588
6     0.413077
7     0.383383
8     0.442105
9     0.410714
10    0.389549
11    0.400000
12    0.487805
13    0.432432
14    0.337580
15    0.375000
16    0.411765
17    0.200000
18    0.913043
19    0.857143
20    1.000000
21    0.312500
22    0.200000
23    0.000000
24    1.000000
25    0.611111
26    1.000000
27    0.666667
28    0.500000
29    0.750000
30    0.857143
35    0.000000
38    0.000000
42    0.000000
43    0.000000
45    0.000000
56    0.500000
Name: is_canceled, dtype: float64

In [159]:
distribution_channel_cancellation_rate = df.groupby('distribution_channel')['is_canceled'].mean().sort_values(ascending=False)

print("Cancellation Rate by Distribution Channel:")
print(distribution_channel_cancellation_rate)

Cancellation Rate by Distribution Channel:
distribution_channel
TA/TO        0.426689
Corporate    0.258199
Direct       0.175855
GDS          0.170455
Name: is_canceled, dtype: float64

In [160]:
country_cancellation_rate = df.groupby('country')['is_canceled'].mean().sort_values(ascending=False)

print("Top 10 Countries by Cancellation Rate:")
print(country_cancellation_rate.head())

Top 10 Countries by Cancellation Rate:
country
GAB    1.0
BHR    1.0
IMN    1.0
BEN    1.0
LIE    1.0
Name: is_canceled, dtype: float64

In [161]:
df['arrival_day_of_week'] = pd.to_datetime(df['arrival_date_year'].astype(str) + '-' + 
                                        df['arrival_date_month'].astype(str) + '-' + 
                                        df['arrival_date_day_of_month'].astype(str)).dt.day_name()

day_of_week_cancellation_rate = df.groupby('arrival_day_of_week')['is_canceled'].mean()

print("Cancellation Rate by Day of the Week:")
print(day_of_week_cancellation_rate)

Cancellation Rate by Day of the Week:
arrival_day_of_week
Friday       0.357844
Monday       0.410905
Saturday     0.358133
Sunday       0.407380
Thursday     0.333625
Tuesday      0.419265
Wednesday    0.412612
Name: is_canceled, dtype: float64

In [162]:
special_requests_cancellation_rate = df.groupby('total_of_special_requests')['is_canceled'].mean()

print("Cancellation Rate based on Number of Special Requests:")
print(special_requests_cancellation_rate)

Cancellation Rate based on Number of Special Requests:
total_of_special_requests
0    0.497661
1    0.279648
2    0.256202
3    0.168908
4    0.096939
5    0.045455
Name: is_canceled, dtype: float64

In [163]:
pivot = pd.pivot_table(df, values='is_canceled', index=['market_segment', 'customer_type'], aggfunc=np.mean)

print("Pivot Table of Cancellation Rate by Market Segment and Customer Type:")
pivot

Pivot Table of Cancellation Rate by Market Segment and Customer Type:

                                is_canceled
market_segment customer_type
Aviation       Group               0.000000
               Transient           0.212963
Complementary  Group               0.000000
               Transient           0.160194
               Transient-Party     0.400000
Corporate      Group               0.230769
               Transient           0.261475
               Transient-Party     0.231003
Direct         Group               0.018868
               Transient           0.162533
               Transient-Party     0.094563
Groups         Contract            0.000000
               Group               0.000000
               Transient           0.985775
               Transient-Party     0.209511
Offline TA/TO  Contract            0.121835
               Group               0.113924
               Transient           0.419692
               Transient-Party     0.196096
Online TA      Group               0.015873
               Transient           0.428319
               Transient-Party     0.056000

In [164]:
country_mapping = {
    'PRT': 'Portugal',
    'IRL': 'Ireland',
    'ESP': 'Spain',
    'DEU': 'Germany',
    'CN': 'China',
    'ITA': 'Italy',
    'GBR': 'United Kingdom',
    'BEL': 'Belgium',
    'RUS': 'Russia',
    'FRA': 'France',
    'MOZ': 'Mozambique',
    'IRN': 'Iran',
    'BRA': 'Brazil',
    'KOR': 'South Korea',
    'AGO': 'Angola',
    'USA': 'United States',
    'ROU': 'Romania',
    'NOR': 'Norway',
    'OMN': 'Oman',
    'ARG': 'Argentina',
    'POL': 'Poland',
    'CHE': 'Switzerland',
    'GRC': 'Greece',
    'NLD': 'Netherlands',
    'DNK': 'Denmark',
    'SWE': 'Sweden',
    'AUS': 'Australia',
    'EST': 'Estonia',
    'CZE': 'Czech Republic',
    'FIN': 'Finland',
    'BWA': 'Botswana',
    'LUX': 'Luxembourg',
    'SVN': 'Slovenia',
    'ALB': 'Albania',
    'IND': 'India',
    'CHN': 'China',
    'MEX': 'Mexico',
    'MAR': 'Morocco',
    'UKR': 'Ukraine',
    'SMR': 'San Marino',
    'LVA': 'Latvia',
    'PRI': 'Puerto Rico',
    'SRB': 'Serbia',
    'CHL': 'Chile',
    'AUT': 'Austria',
    'BLR': 'Belarus',
    'LTU': 'Lithuania',
    'TUR': 'Turkey',
    'ZAF': 'South Africa',
    'ISR': 'Israel',
    'CYM': 'Cayman Islands',
    'ZMB': 'Zambia',
    'CPV': 'Cape Verde',
    'ZWE': 'Zimbabwe',
    'DZA': 'Algeria',
    'CRI': 'Costa Rica',
    'NZL': 'New Zealand',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'HRV': 'Croatia',
    'KAZ': 'Kazakhstan',
    'THA': 'Thailand',
    'COL': 'Colombia',
    'DOM': 'Dominican Republic',
    'MKD': 'North Macedonia',
    'MYS': 'Malaysia',
    'NGA': 'Nigeria',
    'VEN': 'Venezuela',
    'GIB': 'Gibraltar',
    'ARM': 'Armenia',
    'JPN': 'Japan',
    'LKA': 'Sri Lanka',
    'TUN': 'Tunisia',
    'STP': 'Sao Tome and Principe',
    'BGR': 'Bulgaria',
    'TWN': 'Taiwan',
    'AZE': 'Azerbaijan',
    'LBN': 'Lebanon',
    'SVK': 'Slovakia',
    'CMR': 'Cameroon',
    'SGP': 'Singapore',
    'SEN': 'Senegal',
    'PER': 'Peru',
    'EGY': 'Egypt',
    'SAU': 'Saudi Arabia',
    'KNA': 'Saint Kitts and Nevis',
    'JOR': 'Jordan',
    'KWT': 'Kuwait',
    'ETH': 'Ethiopia',
    'PHL': 'Philippines',
    'LIE': 'Liechtenstein',
    'MMR': 'Myanmar',
    'IRQ': 'Iraq',
    'PAN': 'Panama',
    'GEO': 'Georgia',
    'TMP': 'East Timor',
    'MUS': 'Mauritius',
    'ECU': 'Ecuador'
}

In [165]:
df['country'] = df['country'].map(country_mapping)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_stays,arrival_date,room_type_mismatch,arrival_day_of_week
0,Resort Hotel,1,74,2020,January,1,1,1,0,2,...,Transient,57.60,0,0,Canceled,2019-10-20,1,Wednesday,False,Wednesday
1,Resort Hotel,1,62,2020,January,1,1,2,2,2,...,Transient,51.50,0,1,Canceled,2019-12-04,4,Wednesday,False,Wednesday
2,Resort Hotel,1,62,2020,January,1,1,2,2,2,...,Transient,51.50,0,1,Canceled,2019-11-11,4,Wednesday,False,Wednesday
3,Resort Hotel,1,62,2020,January,1,1,2,2,2,...,Transient,51.50,0,1,Canceled,2019-12-04,4,Wednesday,False,Wednesday
4,Resort Hotel,1,71,2020,January,1,1,2,2,1,...,Transient,32.22,0,1,Canceled,2019-10-29,4,Wednesday,False,Wednesday

In [166]:
# Calculate correlation matrix
correlation_matrix = df.corr()

print("Correlation with Cancellation:")
print(correlation_matrix['is_canceled'].sort_values(ascending=False))

ValueError: could not convert string to float: 'Resort Hotel'

In [ ]:
cancelled_perc = df["is_canceled"].value_counts(normalize = True)
print(cancelled_perc)

plt.figure(figsize = (5,4))

plt.title("Reservation status count")

plt.bar(["Not Canceled","Canceled"],df["is_canceled"].value_counts(),edgecolor="k",width = 0.7)
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
sns.barplot(x='hotel', y='is_canceled', data=df, estimator=lambda x: sum(x) / len(x))
plt.title('Cancellation Rate by Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('Cancellation Rate')
plt.show()

In [ ]:
df['day_of_week'] = df['reservation_status_date'].dt.day_name()
plt.figure(figsize=(12, 6))
sns.barplot(x='day_of_week', y='is_canceled', data=df, estimator=lambda x: sum(x) / len(x))
plt.title('Cancellation Rate by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Cancellation Rate')

In [ ]:
# Creating a new column to label cancellations and non-cancellations
df['Cancellation_Status'] = df['is_canceled'].apply(lambda x: 'Canceled' if x == 1 else 'Not Canceled')

# Plotting the bar chart
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='hotel', hue='Cancellation_Status', palette='coolwarm')

# Adding titles and labels
plt.title('Cancellations vs Non-Cancellations by Hotel Type', fontsize=16)
plt.xlabel('Hotel Type', fontsize=14)
plt.ylabel('Number of Bookings', fontsize=14)
plt.legend(title='Booking Status', fontsize=12)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

plt.show()

In [ ]:
resort_hotel = df[df['hotel'] == 'Resort Hotel']
city_hotel = df[df['hotel'] == 'City Hotel']

resort_hotel_cancellation = resort_hotel['is_canceled'].value_counts(normalize=True)
city_hotel_cancellation = city_hotel['is_canceled'].value_counts(normalize=True)

resort_hotel_adr = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel_adr = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize=(20, 8))
plt.title("Average Daily Rate in City and Resort Hotels", fontsize=30)

plt.plot(resort_hotel_adr.index, resort_hotel_adr['adr'], label='Resort Hotel', color='blue', linewidth=2)

plt.plot(city_hotel_adr.index, city_hotel_adr['adr'], label='City Hotel', color='orange', linewidth=2)

plt.xlabel('Reservation Status Date', fontsize=16)
plt.ylabel('Average Daily Rate (ADR)', fontsize=16)
plt.xticks(rotation=45)
plt.legend(fontsize=14)

plt.show()

In [ ]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

df['reservation_month'] = df['reservation_status_date'].dt.to_period('M')

monthly_reservations = df.groupby(['reservation_month', 'is_canceled']).size().unstack(fill_value=0)

monthly_reservations = monthly_reservations.reset_index()

monthly_reservations.columns = ['Month', 'Not Canceled', 'Canceled']

plt.figure(figsize=(14, 8))

bar_width = 0.4
index = np.arange(len(monthly_reservations['Month']))

plt.bar(index, monthly_reservations['Not Canceled'], bar_width, label='Not Canceled', color='green')

plt.bar(index + bar_width, monthly_reservations['Canceled'], bar_width, label='Canceled', color='red')

plt.title('Monthly Reservations: Canceled vs Not Canceled', fontsize=20)
plt.xlabel('Month', fontsize=16)
plt.ylabel('Number of Reservations', fontsize=16)
plt.xticks(index + bar_width / 2, monthly_reservations['Month'].astype(str), rotation=45)
plt.legend(fontsize=14)

plt.show()

In [ ]:
df['year_month'] = df['arrival_date_year'].astype(str) + '-' + df['arrival_date_month']

year_month_cancellation_rate = df.groupby('year_month')['is_canceled'].mean()

plt.figure(figsize=(12, 6))
year_month_cancellation_rate.plot()
plt.title('Cancellation Rate by Year-Month')
plt.xlabel('Year-Month')
plt.ylabel('Cancellation Rate')
plt.xticks(rotation=45)
plt.show()

In [ ]:
adr_bins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
adr_labels = ['<50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450+']

df['adr_bin'] = pd.cut(df['adr'], bins=adr_bins, labels=adr_labels, right=False)

cancellation_rates = df.groupby('adr_bin')['is_canceled'].mean()

plt.figure(figsize=(12, 6))
plt.plot(cancellation_rates.index, cancellation_rates.values, marker='o', linestyle='-', color='b')

plt.xlabel('ADR Range')
plt.ylabel('Average Cancellation Rate')
plt.title('Average Cancellation Rate by ADR Range')
plt.grid(True)

plt.show()

In [ ]:
adr_bins = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]
adr_labels = ['<50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-450', '450+']

df['adr_bin'] = pd.cut(df['adr'], bins=adr_bins, labels=adr_labels, right=False)

cancellation_rates = df.groupby('adr_bin')['is_canceled'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(data=cancellation_rates, x='adr_bin', y='is_canceled', palette='viridis')

plt.xlabel('ADR Range')
plt.ylabel('Average Cancellation Rate')
plt.title('Average Cancellation Rate by ADR Range')
plt.xticks(rotation=45)  
plt.grid(visible = False)

plt.show()

In [ ]:
plt.figure(figsize = (10,6))


plt.pie(cancelation_by_country["is_canceled"],labels = cancelation_by_country["Country_Name"],autopct='%1.1f%%')
plt.title("Top 10 Countries by most Cancelation ")

plt.show()

In [ ]:
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.histplot(df['lead_time'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Lead Time')
plt.xlabel('Lead Time (days)')
plt.ylabel('Frequency')
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, x='hotel', y='adr', palette='Set2')
plt.title('ADR Distribution by Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('ADR')
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='arrival_date_month', hue='is_canceled', palette='Set1')
plt.title('Monthly Cancellations Count')
plt.xlabel('Month')
plt.ylabel('Number of Cancellations')
plt.xticks(rotation=45)
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
sns.scatterplot(data=df, x='lead_time', y='adr', hue='is_canceled', palette='coolwarm', alpha=0.6)
plt.title('ADR vs. Lead Time')
plt.xlabel('Lead Time (days)')
plt.ylabel('ADR')
plt.show()

In [ ]:
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

adr_over_time = df.groupby('reservation_status_date')['adr'].mean()

plt.figure(figsize=(12, 6))
adr_over_time.plot(kind='line', color='green')
plt.title('Average ADR Over Time')
plt.xlabel('Date')
plt.ylabel('Average ADR')
plt.show()

In [ ]:
df_numeric = df.select_dtypes(include=['number'])

correlation_matrix = df_numeric.corr()

plt.figure(figsize=(14, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', vmin=-1, vmax=1, linewidths=0.5)
plt.title('Correlation Matrix of All Numeric Features')
plt.show()

In [ ]:
df['is_canceled'] = pd.to_numeric(df['is_canceled'], errors='coerce')

correlation_matrix = df.corr()

cancellation_correlation = correlation_matrix[['is_canceled']].sort_values(by='is_canceled', ascending=False)

plt.figure(figsize=(12, 8))
sns.heatmap(cancellation_correlation, annot=True, cmap='coolwarm', fmt='.2f', vmin=-1, vmax=1)
plt.title('Correlation of Cancellation with Other Features')
plt.show()

In [ ]:
import mysql.connector
from sqlalchemy import create_engine

db_config = {
    'user': 'root',
    'password': '9989',
    'host': 'localhost',
}

conn = mysql.connector.connect(**db_config)

cursor = conn.cursor()

cursor.execute("CREATE DATABASE IF NOT EXISTS hotel_db")

cursor.close()
conn.close()

In [ ]:
db_config['database'] = 'hotel_db'
conn = mysql.connector.connect(**db_config)
cursor = conn.cursor()

create_table_query = """
CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hotel VARCHAR(255),
    is_canceled TINYINT(1),
    lead_time INT,
    arrival_date_year INT,
    arrival_date_month VARCHAR(20),
    arrival_date_week_number INT,
    arrival_date_day_of_month INT,
    stays_in_weekend_nights INT,
    stays_in_week_nights INT,
    adults INT,
    children INT,
    babies INT,
    meal VARCHAR(20),
    country VARCHAR(100),
    market_segment VARCHAR(50),
    distribution_channel VARCHAR(50),
    is_repeated_guest TINYINT(1),
    previous_cancellations INT,
    previous_bookings_not_canceled INT,
    reserved_room_type VARCHAR(10),
    assigned_room_type VARCHAR(10),
    booking_changes INT,
    deposit_type VARCHAR(20),
    agent FLOAT,
    company FLOAT,
    days_in_waiting_list INT,
    customer_type VARCHAR(50),
    adr FLOAT,
    required_car_parking_spaces INT,
    total_of_special_requests INT,
    reservation_status VARCHAR(20),
    reservation_status_date DATE
)
"""

cursor.execute(create_table_query)

cursor.close()

In [ ]:
engine = create_engine(f"mysql+mysqlconnector://{db_config['user']}:{db_config['password']}@{db_config['host']}/{db_config['database']}")

df.to_sql('bookings', con=engine, if_exists='replace', index=False)

print("Data imported successfully!")
conn.close()

In [170]:
df.isna().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                             331
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                              5664
company                           38377
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
total_stays                           0
arrival_date                          0
room_type_mismatch                    0
arrival_day_of_week                   0
dtype: int64

In [174]:
df["country"]=df["country"].fillna("Undefined")

In [176]:
df=df.drop(columns=["agent","company"])

In [178]:
df.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
total_stays                       0
arrival_date                      0
room_type_mismatch                0
arrival_day_of_week               0
dtype: int64

In [180]:
import mysql.connector
from sqlalchemy import create_engine

db_config = {
    'user': 'root',
    'password': '9989',
    'host': 'localhost',
}

conn = mysql.connector.connect(**db_config)

cursor = conn.cursor()

cursor.execute("CREATE DATABASE IF NOT EXISTS hotel_db")

cursor.close()
conn.close()

In [184]:
db_config['database'] = 'hotel_db'
conn = mysql.connector.connect(**db_config)
cursor = conn.cursor()

create_table_query = """
CREATE TABLE IF NOT EXISTS bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hotel VARCHAR(255),
    is_canceled TINYINT(1),
    lead_time INT,
    arrival_date_year INT,
    arrival_date_month VARCHAR(20),
    arrival_date_week_number INT,
    arrival_date_day_of_month INT,
    stays_in_weekend_nights INT,
    stays_in_week_nights INT,
    adults INT,
    children INT,
    babies INT,
    meal VARCHAR(20),
    country VARCHAR(100),
    market_segment VARCHAR(50),
    distribution_channel VARCHAR(50),
    is_repeated_guest TINYINT(1),
    previous_cancellations INT,
    previous_bookings_not_canceled INT,
    reserved_room_type VARCHAR(10),
    assigned_room_type VARCHAR(10),
    booking_changes INT,
    deposit_type VARCHAR(20),
    agent FLOAT,
    company FLOAT,
    days_in_waiting_list INT,
    customer_type VARCHAR(50),
    adr FLOAT,
    required_car_parking_spaces INT,
    total_of_special_requests INT,
    reservation_status VARCHAR(20),
    reservation_status_date DATE
)
"""

cursor.execute(create_table_query)

cursor.close()

True

In [186]:
engine = create_engine(f"mysql+mysqlconnector://{db_config['user']}:{db_config['password']}@{db_config['host']}/{db_config['database']}")

df.to_sql('bookings', con=engine, if_exists='replace', index=False)

print("Data imported successfully!")
conn.close()

Data imported successfully!